// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1BPuLmfyISYZLBgQ0rnDY9shwpaw7FPk',
    appId: '1:2265953707:web:bf9bca2181c96ca5420eee',
    messagingSenderId: '2265953707',
    projectId: 'onlineticketing-97072',
    authDomain: 'onlineticketing-97072.firebaseapp.com',
    storageBucket: 'onlineticketing-97072.appspot.com',
    measurementId: 'G-JTLWLSY188',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJ8TvEE8IphoPAA-jiLPlcsqGWa9qU-k',
    appId: '1:2265953707:android:e67fa7f3a8eb41c2420eee',
    messagingSenderId: '2265953707',
    projectId: 'onlineticketing-97072',
    storageBucket: 'onlineticketing-97072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDR7ni6xoZ63-it_A1BfcM4a8y-a4WS4',
    appId: '1:2265953707:ios:74fcc6d741a64307420eee',
    messagingSenderId: '2265953707',
    projectId: 'onlineticketing-97072',
    storageBucket: 'onlineticketing-97072.appspot.com',
    iosBundleId: 'com.example.onlineTicketing',
  );
}
